const String javascript PROGMEM = " $(document).ready(function(){\r\n"
            "  setInterval(getData,1000);\r\n"
            " function getData(){\r\n"
            "  $.ajax({\r\n"
            "  type:\"GET\",\r\n"
            "  url:\"data\",\r\n"
            "  success: function(data){\r\n"
            "  $('#heading-value').val(data);\r\n"
            "  theta = data - 90;\r\n"
            "  $('#arrow').css({'transform' : 'rotate('+ theta +'deg)'});\r\n"
            "}\r\n"
            "}).done(function() {\r\n"
            " console.log('ok'); "
            "})\r\n"
            "}\r\n"
            "});";
