const String page PROGMEM = "<head>"
            " <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
            " <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>"
            " <script src='/jscript.js'></script>"
            " <link href='https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap' rel='stylesheet'>"
            " <style>"
            " body{"
            " background-color:white;"
            " font-family: 'Roboto', sans-serif;" 
            "}"
            "#tmm-logo{"
            "  margin-top: 100px;"
            "  margin-left: 50%;"
            "  width:50%;"
            "}"
            "#arrow{"
            "width: 50%;"
            "margin-top: 50px;"
            "margin-left: 20%;"
            "$('#arrow').css({'transform' : 'rotate(270deg)'});"
            "}"
            "</style>"
            " </head>"
            " <body>"
            " <h1>ESP32 Magnetometer</h1>"
            " <p>Uses a NodeMCU-32S and HMC5883L Magnetometer</p>"
            " <p><a href='https://www.teachmemicro.com/esp32-magnetometer-hmc5883l'>Full tutorial</a></p>"
            " <label for='heading-value'>Heading (degrees from N):</label> <input type='text' id='heading-value'>""</p>\r\n" 
            " <img id='arrow' src='https://i.imgur.com/5buESn2.png'/>\r\n "
            " <img id='tmm-logo' src='https://i.imgur.com/G80eVhL.png' />"
            "</body>";
