// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3sxz8LTLgtvdkvBAaLvZO7gBLqzuLM_A',
    appId: '1:825213372220:web:8f22d587cfc44237848039',
    messagingSenderId: '825213372220',
    projectId: 'rudra-x',
    authDomain: 'rudra-x.firebaseapp.com',
    databaseURL: 'https://rudra-x-default-rtdb.firebaseio.com',
    storageBucket: 'rudra-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV9xOK_EVmbGvPthGtRQo4189Y2lO0aQ4',
    appId: '1:825213372220:android:ead94c9f344abc05848039',
    messagingSenderId: '825213372220',
    projectId: 'rudra-x',
    databaseURL: 'https://rudra-x-default-rtdb.firebaseio.com',
    storageBucket: 'rudra-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgG2DkuZULA9pFIsGiwv2r2gU3DHVIaFQ',
    appId: '1:825213372220:ios:ca29ea71ebaa07a3848039',
    messagingSenderId: '825213372220',
    projectId: 'rudra-x',
    databaseURL: 'https://rudra-x-default-rtdb.firebaseio.com',
    storageBucket: 'rudra-x.appspot.com',
    iosClientId: '825213372220-kibrqor0pbko54rqpl60mi6mhftei873.apps.googleusercontent.com',
    iosBundleId: 'com.example.rudraApp',
  );
}
